# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/metadata-syntax-for-github-actions
name: 'NPM or Yarn install with caching'
description: 'Install npm dependencies with caching'
author: 'Gleb Bahmutov'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'yellow'
  icon: 'command'
inputs:
  working-directory:
    description: 'Working directory to specify subfolder in which dependencies are defined'
    required: false
  useLockFile:
    description: 'Option to enable or disable use of a lock file (package-lock.json/yarn.lock)'
    required: false
  useRollingCache:
    description: Option to enable restoring a cache that doesn't exactly match the lockfile, and expire once a month to keep it from only growing larger
    required: false
  install-command:
    description: 'Custom install command to use'
    required: false
